
drop database if exists church_db;

create database church_db;

use church_db;

CREATE TABLE `PERSONS` (
  `PID` varchar(255) PRIMARY KEY,
  `FIRST_NAME` varchar(50),
  `LAST_NAME` varchar(50),
  `DATE_OF_BIRTH` date,
  `TYPE` enum('P','N'),
  `GENDER` enum('MALE','FEMALE'),
  `CLAN_ID` varchar(255)
);

CREATE TABLE `CLAN` (
  `CID` varchar(255) PRIMARY KEY,
  `TRIBE_ID` varchar(255),
  `CLAN_NAME` varchar(50)
);

CREATE TABLE `TRIBE` (
  `TRIBE_ID` varchar(255) PRIMARY KEY,
  `TRIBE_NAME` varchar(50)
);

CREATE TABLE `LOCATION` (
  `LOCATION_ID` varchar(255) PRIMARY KEY,
  `LOC_NAME` varchar(50)
);

CREATE TABLE `DEATH` (
  `DEATH_ID` varchar(255) PRIMARY KEY,
  `DEATH_NO` int,
  `PID` varchar(255),
  `SO_OR_DO` varchar(50),
  `DISTRICT_ID` varchar(255),
  `BAPTISM_ID` varchar(255),
  `MARRIAGE_ID` varchar(255),
  `last_rite` enum('YES','NO'),
  `BURIAL_PLACE` varchar(255),
  `BURIAL_DATE` date,
  `priest_id` varchar(255)
);

CREATE TABLE `G_PERSONS` (
  `G_PERSONS_ID` varchar(255) PRIMARY KEY,
  `G_FATHER` varchar(255),
  `S_O_father` varchar(50),
  `G_MOTHER` varchar(255),
  `S_O_mother` varchar(50)
);

CREATE TABLE `BAPTISM` (
  `BAPTISM_ID` varchar(255) PRIMARY KEY,
  `BAPTISM_NO` int,
  `MOTHER_ID` varchar(255),
  `FATHER_ID` varchar(255),
  `BAPTISM_AT` varchar(255),
  `g_PERSONS_ID` varchar(255)
);

CREATE TABLE `CONFIRMATION` (
  `CONFIMARTION_ID` varchar(255) PRIMARY KEY,
  `CONFIMATION_NO` int,
  `DATE_` DATE,
  `PID` varchar(255),
  `MOTHER_ID` varchar(255),
  `FATHER_ID` varchar(255),
  `NO_MEN_BAPT` int,
  `g_PERSONS_ID` varchar(255),
  `PRIEST_ID` varchar(255),
  `BAPTUM_DIE` varchar(50),
  `AT` varchar(255)
);

CREATE TABLE `MARRIAGE_` (
  `MARRIAGE_ID` varchar(255) PRIMARY KEY,
  `DATE_` date,
  `CHURCH_OF` varchar(50),
  `BANNS_NO` int,
  `DELEGATE` varchar(50),
  `PRIEST_ID` varchar(255),
  `MALE_WITNESS_ID` varchar(255),
  `FEMALE_WITNESS_ID` varchar(255),
  `M_CERT_NO` int
);

CREATE TABLE `COUPLES` (
  `C_MEMBER_ID` varchar(255) PRIMARY KEY,
  `MARRIAGE_ID` varchar(255),
  `PERSON_ID` varchar(255),
  `MOTHER_ID` varchar(255),
  `FATHER_ID` varchar(255),
  `BAPTISM` varchar(255),
  `DOMICILE` varchar(50)
);

CREATE TABLE `marriage_contract` (
  `CONTRANT_ID` varchar(255) PRIMARY KEY,
  `MARRIAGE_ID` varchar(255),
  `BY_CATHOLIC` enum('YES','NO'),
  `DATE_` date,
  `LOCATION_ID` varchar(255)
);

CREATE TABLE `DISPENSATION` (
  `DISP_ID` varchar(255) PRIMARY KEY,
  `MARRIAGE_ID` varchar(255),
  `D_FROM` Varchar(50),
  `GIVEN_BY` varchar(50),
  `EMPEPIMENTS_OF` varchar(50),
  `DATE_` date,
  `LOCATION_ID` varchar(255)
);

ALTER TABLE `PERSONS` ADD FOREIGN KEY (`CLAN_ID`) REFERENCES `CLAN` (`CID`);

ALTER TABLE `CLAN` ADD FOREIGN KEY (`TRIBE_ID`) REFERENCES `TRIBE` (`TRIBE_ID`);

ALTER TABLE `DEATH` ADD FOREIGN KEY (`PID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `DEATH` ADD FOREIGN KEY (`DISTRICT_ID`) REFERENCES `LOCATION` (`LOCATION_ID`);

ALTER TABLE `DEATH` ADD FOREIGN KEY (`BAPTISM_ID`) REFERENCES `BAPTISM` (`BAPTISM_ID`);

ALTER TABLE `DEATH` ADD FOREIGN KEY (`MARRIAGE_ID`) REFERENCES `MARRIAGE_` (`MARRIAGE_ID`);

ALTER TABLE `DEATH` ADD FOREIGN KEY (`BURIAL_PLACE`) REFERENCES `LOCATION` (`LOCATION_ID`);

ALTER TABLE `DEATH` ADD FOREIGN KEY (`priest_id`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `G_PERSONS` ADD FOREIGN KEY (`G_FATHER`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `G_PERSONS` ADD FOREIGN KEY (`G_MOTHER`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `BAPTISM` ADD FOREIGN KEY (`MOTHER_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `BAPTISM` ADD FOREIGN KEY (`FATHER_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `BAPTISM` ADD FOREIGN KEY (`BAPTISM_AT`) REFERENCES `LOCATION` (`LOCATION_ID`);

ALTER TABLE `BAPTISM` ADD FOREIGN KEY (`g_PERSONS_ID`) REFERENCES `G_PERSONS` (`G_PERSONS_ID`);

ALTER TABLE `CONFIRMATION` ADD FOREIGN KEY (`PID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `CONFIRMATION` ADD FOREIGN KEY (`MOTHER_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `CONFIRMATION` ADD FOREIGN KEY (`FATHER_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `CONFIRMATION` ADD FOREIGN KEY (`g_PERSONS_ID`) REFERENCES `G_PERSONS` (`G_PERSONS_ID`);

ALTER TABLE `CONFIRMATION` ADD FOREIGN KEY (`PRIEST_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `CONFIRMATION` ADD FOREIGN KEY (`AT`) REFERENCES `LOCATION` (`LOCATION_ID`);

ALTER TABLE `MARRIAGE_` ADD FOREIGN KEY (`DELEGATE`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `MARRIAGE_` ADD FOREIGN KEY (`PRIEST_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `MARRIAGE_` ADD FOREIGN KEY (`MALE_WITNESS_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `MARRIAGE_` ADD FOREIGN KEY (`FEMALE_WITNESS_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `COUPLES` ADD FOREIGN KEY (`MARRIAGE_ID`) REFERENCES `MARRIAGE_` (`MARRIAGE_ID`);

ALTER TABLE `COUPLES` ADD FOREIGN KEY (`PERSON_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `COUPLES` ADD FOREIGN KEY (`MOTHER_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `COUPLES` ADD FOREIGN KEY (`FATHER_ID`) REFERENCES `PERSONS` (`PID`);

ALTER TABLE `COUPLES` ADD FOREIGN KEY (`BAPTISM`) REFERENCES `BAPTISM` (`BAPTISM_ID`);

ALTER TABLE `marriage_contract` ADD FOREIGN KEY (`MARRIAGE_ID`) REFERENCES `MARRIAGE_` (`MARRIAGE_ID`);

ALTER TABLE `marriage_contract` ADD FOREIGN KEY (`LOCATION_ID`) REFERENCES `LOCATION` (`LOCATION_ID`);

ALTER TABLE `DISPENSATION` ADD FOREIGN KEY (`MARRIAGE_ID`) REFERENCES `MARRIAGE_` (`MARRIAGE_ID`);

ALTER TABLE `DISPENSATION` ADD FOREIGN KEY (`LOCATION_ID`) REFERENCES `LOCATION` (`LOCATION_ID`);
